IF EXISTS (SELECT *FROM sys.databases WHERE NAME='QuanLySinhVien1')
DROP TABLE QuanLySinhVien1
GO
CREATE DATABASE QuanLySinhVien1
GO
USE QuanLySinhVien1
GO
CREATE TABLE SINHVIEN
(
		MA_SINHVIEN VARCHAR(10) NOT NULL,
		HOTEN NVARCHAR(100),
		NAMSINH INT,
		DANTOC NVARCHAR(20),
		MALOP VARCHAR(10) NOT NULL,
CONSTRAINT PK_SINHVIEN PRIMARY KEY(MA_SINHVIEN)
)
alter table SINHVIEN 
add constraint FK_SV_LOP foreign key (MALOP)references LOP(MA_LOP)
--INSERT TABLE SINHVIEN
INSERT INTO SINHVIEN VALUES('0212001',N'Trọng"sơ-vin"',1997,N'KINH','TH2002/01')
INSERT INTO SINHVIEN VALUES('0212002',N'Đức cọt',1996,N'KINH','TH2002/01')
INSERT INTO SINHVIEN VALUES('0212003',N'Phượng súp lơ',1995,N'KINH','TH2002/02')
INSERT INTO SINHVIEN VALUES('0212004',N'Lâm Tây',1993,N'KINH','TH2002/02')
INSERT INTO SINHVIEN VALUES('0311001',N'Chinh Đen',1997,N'KINH','VN2003/01')
INSERT INTO SINHVIEN VALUES('0311001',N'Duy Pinky',1996,N'KINH','VN2003/01')
CREATE TABLE LOP
(
		MA_LOP VARCHAR(10) NOT NULL,
		MA_KHOAHOC VARCHAR(10) NOT NULL,
		MA_KHOA VARCHAR(10) NOT NULL,
		MA_CHUONGTRINH VARCHAR(10) NOT NULL,
		SOTHUTU INT,
CONSTRAINT PK_LOP PRIMARY KEY (MA_LOP)
)
alter table LOP
add constraint FK_LOP_KH foreign key(MA_KHOAHOC)references KHOAHOC(MA_KHOAHOC),
constraint FK_LOP_K foreign key(MA_KHOA)references KHOA(MA_KHOA)

--INSERT TABLE LOP
INSERT INTO LOP VALUES('TH2002/01','K2002','BDVN','CQ',1)
INSERT INTO LOP VALUES('TH2002/02','K2002','BDVN','CQ',2)
INSERT INTO LOP VALUES('VN2003/01','K2003','BDVN','CQ',1)
CREATE TABLE MONHOC
(
		MA_MONHOC VARCHAR(10) NOT NULL,
		TENMONHOC NVARCHAR(100),
		MA_KHOA VARCHAR(10) NOT NULL,
CONSTRAINT PK_MONHOC PRIMARY KEY(MA_MONHOC)
)
--INSERT TABLE MONHOC
INSERT INTO MONHOC VALUES('THT01',N'trung vệ','BDVN')
INSERT INTO MONHOC VALUES('VNT01',N'tiền vệ','BDVN')
INSERT INTO MONHOC VALUES('THT02',N'tiền đạo','BDVN')
INSERT INTO MONHOC VALUES('THCS01',N'thủ môn','BDVN')
INSERT INTO MONHOC VALUES('THCS2',N'tiền vệ và hậu vệ','BDVN')

UPDATE SINHVIEN
SET HOTEN = N'Nguyễn Quang Hải', MALOP = 'TH2002/02'
WHERE MA_SINHVIEN = '0212003'
UPDATE LOP
SET MA_KHOA = 'K2003'
WHERE MA_LOP = 'TH2002/03'
UPDATE MONHOC
SET TENMONHOC  = N'tiền vệ'
WHERE MA_KHOA = 'THTO1'

--Xóa 1 dòng trong bảng Sinh Viên
ALTER TABLE MONHOC DROP CONSTRAINT FK_SV_LOP
GO
DELETE FROM SINHVIEN
WHERE MALOP = 'TH2002/02'

--Xóa 1 dòn trong bảng Lop Hoc
ALTER TABLE MONHOC DROP CONSTRAINT FK_L_KH
DELETE FROM LOP
WHERE MA_LOP = 'TH2002/01'

--Xóa 1 dòng trong bảng ChiTietLopHoc
DELETE FROM MONHOC
WHERE MA_KHOA = 'THT02'